angular.module('mlearningApp').controller('unidadController', function ($scope, globales) {

    $scope.unidad = 'unidadController';
    $scope.unidades = [];
    $scope.pags = [];
    ///////combobox/////////
    $scope.etiquetas = [
        {id:1,name:'fisica1'},
        {id:2,name:'fisica2'},
        {id:3,name:'fisica3'}
    ];
  
    ///funciones
    $scope.unidadActual = {};
    $scope.crearUnidad = function () {

        $.ajax(
        {
            url: saveUnitURL,
            type: "POST",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify($scope.unidadActual),
            success: function (data, textStatus, jqXHR) {
                console.log(data);
                if(data.errors.length==0)
                {
                    $scope.redireccionar(data.url);
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {

            }
        });
        
        console.log('crear Unidad',$scope.unidadActual);
        $scope.unidades.push($scope.unidadActual);

         globales.save('unidadActual',$scope.unidadActual);
         //$('#unitForm').submit();
    }
    $scope.cancelarUnidad = function () {
        //console.log('cancelar Unidad', 'Regresar a crear Unidad');
        window.history.back();
    }
    
    
    
    
    
    
    ////////////////aparte/////////////////
  $scope.guitarVariable = [  {
			"name" 		 : "Acoustic Guitar",
			"description": "Acoustic, electro-acoustic and classical guitars, from leading brands in world.",
			"longDescription" : "An acoustic guitar is a guitar that uses only acoustic (as opposed to electronic) means to transmit the strings vibrational energy to the air in order to produce a sound. This typically involves the use of a sound board and a sound box to amplify the vibrations of the string. The source of sound in an acoustic guitar is the string, which is plucked with the fingers or with a plectrum. The string vibrates at a fundamental frequency but also creates many harmonics at different frequencies. The frequencies produced depend on string length, mass, and tension. The string causes the soundboard and sound box to vibrate, and as these have their own resonances at certain frequencies, they amplify some string harmonics more strongly than others, hence affecting the timbre produced by the instrument.",
			"image"	:  "Acoustic",
			"price" : "23.78",
			"dateAdded" : "1403926823000",
			"category" : "expensive"
		},
		{
			"name" 		 : "Electric Guitar",
			"description": "Ever-popular solid-body guitars, to hollow-body guitars and archtops.",
			"longDescription" : "An electric guitar is a guitar that uses a pickup to convert the vibration of its strings into electrical impulses. The most common guitar pickup uses the principle of direct electromagnetic induction. The signal generated by an electric guitar is too weak to drive a loudspeaker, so it is amplified before sending it to a loudspeaker. Since the output of an electric guitar is an electric signal, the signal may easily be altered using electronic circuits to add color to the sound. Often the signal is modified using effects such as reverb and distortion.",
			"image"	:  "Electric",
			"price" : "18.34",
			"dateAdded" : "1399779623000",
			"category" : "expensive"
		}
    
                          ];
    
    
});

